export type PrintifyProduct = {
  printifyId: string
  name: string
  tagline: string
  description: string
  priceCents: number
  currency: "usd"
  color: string
  sizes: string[]
  image: string
  category: "polos" | "hats" | "shorts" | "tees" | "hoodies" | "accessories"
  printifyVariantId: string
  sku: string
  costCents: number
}

export const PRINTIFY_PRODUCTS: PrintifyProduct[] = [
  // 33 products synced from Printify shop 22767091
  {
    printifyId: '6977d6954640c1548405afa2',    name: 'Bomber Dinger Polo',    tagline: 'Bomber Dinger Polo',    description: 'This lightweight polo brings quiet personality to warm-weather days. The all-over print folds tiny celestial and botanical motifs into a dark backdrop, so it reads refined at a glance and reveals playful detail up close. Breathable, quick-drying polyester keeps the silhouette crisp whether you’re commuting, on a patio, or headed to a relaxed meet-up. The pointed collar and three-button placket give a smart frame without feeling stiff—wear it buttoned for structure or open at the throat for a ...',    priceCents: 4999,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/6977d6954640c1548405afa2/112163/106286/bomber-dinger-polo.jpg?camera_label=front',    category: "polos",    printifyVariantId: '112163',    sku: '21181668047041042559',    costCents: 4478,  },
  {
    printifyId: '6931e992efc6b8a3fc00f9ec',    name: 'Embroidered Quarter-Zip Pullover — White Athletic Adidas-Inspired Top',    tagline: 'Embroidered Quarter-Zip Pullover — White Athletic Adidas-Inspired Top',    description: 'A lightweight quarter-zip pullover that feels like a cool morning on the course or a quiet sunrise run. The relaxed silhouette moves with you—no tugging at the shoulders—while the self-mock collar and clean hems keep the look streamlined. Built for activity, the hydrophilic finish wicks sweat fast and the UPF 50+ weave shields skin when you’re under the sun. Subtle embroidered detailing and a contrast logo on the sleeve add quiet, sporty polish. It layers easily over tees or under jackets and...',    priceCents: 10533,    currency: 'usd',    color: 'White',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],    image: 'https://images-api.printify.com/mockup/6931e992efc6b8a3fc00f9ec/118445/109474/embroidered-quarter-zip-pullover-white-athletic-adidas-inspired-top.jpg?camera_label=front',    category: "hoodies",    printifyVariantId: '118445',    sku: '43724362765858083262',    costCents: 6320,  },
  {
    printifyId: '691d4be5cf0d5102c60df526',    name: 'Dinger Don Crew Neck',    tagline: 'Dinger Don Crew Neck',    description: 'A cozy, midweight crewneck that feels like a slow exhale on a frosty morning. This garment-dyed sweatshirt carries a lived-in softness from 80% ring-spun cotton and 20% polyester, with a relaxed fit that layers easily over shirts or tees. The Dinger Don crew neck detail — a subtle half-moon patch at the back — gives the neckline character while the ribbed collar, cuffs, and hem hold shape through repeated wear. Necktape and a sewn-in twill label add comfort and durability, and OEKO-TEX certif...',    priceCents: 5799,    currency: 'usd',    color: 'White',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/691d4be5cf0d5102c60df526/102429/99007/dinger-don-crew-neck.jpg?camera_label=front',    category: "tees",    printifyVariantId: '96841',    sku: '20646860224207649307',    costCents: 4116,  },
  {
    printifyId: '6916a36be1bc399c020dbe58',    name: 'Golf Warmup Hoodie with Dinger Don',    tagline: 'Golf Warmup Hoodie with Dinger Don',    description: 'This golf warmup hoodie features a dinger don gopher character design, giving off a sporty and fun vibe. It is perfect for golf enthusiasts looking to stay warm and stylish on the course. Ideal for golf events, tournaments, and casual wear.<br/><br/>Product features<br/>- 100% Polyester fabric for durability<br/>- Moisture-wicking material to keep you cool<br/>- Lightweight design for comfort<br/>- UPF +50 sun protection<br/>- Assembled in the USA with globally sourced parts<br/><br/>Care ins...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],    image: 'https://images-api.printify.com/mockup/6916a36be1bc399c020dbe58/101916/98551/golf-warmup-hoodie-with-dinger-don.jpg?camera_label=front',    category: "hoodies",    printifyVariantId: '101916',    sku: '13822700533113673456',    costCents: 3784,  },
  {
    printifyId: '68f11fff6108cebe5008d50e',    name: 'Footballer Player Tee',    tagline: 'Footballer Player Tee',    description: 'This oversized tee embodies the grit and toughness of a football player among the team. It exudes a rugged, sporty vibe and is perfect for sports enthusiasts and football fans. Ideal for game days, sports events, and casual wear.<br/><br/>Product features<br/>- Dropped shoulders for a relaxed fit<br/>- Shoulder-to-shoulder tape for stability<br/>- Double needle stitch on hems for durability<br/>- Made from 100% carded cotton<br/>- Medium-heavy fabric for a quality feel<br/><br/>Care instructi...',    priceCents: 3899,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/68f11fff6108cebe5008d50e/102276/98719/footballer-player-tee.jpg?camera_label=front',    category: "tees",    printifyVariantId: '103432',    sku: '28513569401159313996',    costCents: 2721,  },
  {
    printifyId: '68ce1e546d18a047f20632be',    name: 'Dinger Don Hat',    tagline: 'Dinger Don Hat',    description: 'This cap features an embroidered design of golfing dinger Don the gopher, perfect for those who love golf and quirky characters. It adds a fun and playful vibe to any outfit, making it a great accessory for casual outings or sports events. Ideal for golf enthusiasts, sports fans, and those who appreciate unique headwear. Perfect for Father\'s Day, birthdays, or golf-themed parties.<br/><br/>Product features<br/>- Six-panel structured design with eyelets and curved visor<br/>- One size fits mos...',    priceCents: 2999,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/68ce1e546d18a047f20632be/118701/109496/dinger-don-hat.jpg?camera_label=front',    category: "hats",    printifyVariantId: '118701',    sku: '12972188858629161347',    costCents: 2356,  },
  {
    printifyId: '68ce1b930b3d660c3a0534d0',    name: 'Dingersville Classic Dad Cap, Casual Hat for Golf Lovers, Gift for Fathers\' Day, Embroidered Dad Hat, Unisex Summer Cap',    tagline: 'Dingersville Classic Dad Cap, Casual Hat for Golf Lovers, Gift for Fathers\' Day, Embroidered Dad Hat, Unisex Summer Cap',    description: 'Elevate your everyday style with this Classic Dad Cap, designed for comfort and versatility. Ideal for casual outings, it effortlessly blends with a variety of outfits, from beachwear to weekend casual. Its relaxed fit provides a laid-back vibe, making it perfect for outdoor activities or simply lounging on a sunny day. This cap is great for anyone who appreciates simple yet functional accessories, making it a thoughtful gift for fathers, friends, or anyone who loves a classic look. It\'s an e...',    priceCents: 3347,    currency: 'usd',    color: 'White',    sizes: [],    image: 'https://images-api.printify.com/mockup/68ce1b930b3d660c3a0534d0/105381/102724/dingersville-classic-dad-cap-casual-hat-for-golf-lovers-gift-for-fathers-day-embroidered-dad-hat-unisex-summer-cap.jpg?camera_label=back',    category: "hats",    printifyVariantId: '105381',    sku: '12750256314713147069',    costCents: 2095,  },
  {
    printifyId: '68ce192cc2eb10522b011c98',    name: 'Golf Cart Dinger Don',    tagline: 'Golf Cart Dinger Don',    description: 'This Polo Shirt features a fun pattern with Dinger Don the gopher driving a golf cart, giving off a playful and casual vibe. Perfect for golf enthusiasts or those who enjoy quirky designs. Ideal for casual outings, golf games, Father\'s Day, or leisure activities.<br/><br/>Product features<br/>- 100% Polyester for durability and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Extra light fabric for comfort (4.13 oz/yd²)<br/...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68ce192cc2eb10522b011c98/112163/106286/golf-cart-dinger-don.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '63399205702171107985',    costCents: 4478,  },
  {
    printifyId: '68ce17f56d18a047f206316d',    name: 'Stylish AOP Unisex Polo Shirt | Vibrant Patterned Shirt for Casual Outings, Summer Vacations, Gifts, Parties, Tropical Vibes',    tagline: 'Stylish AOP Unisex Polo Shirt | Vibrant Patterned Shirt for Casual Outings, Summer Vacations, Gifts, Parties, Tropical Vibes',    description: 'Elevate your wardrobe with this stylish Unisex Polo Shirt, designed for comfort and flair. Crafted from 100% polyester, it feels lightweight and breathable, ideal for warm days or casual outings. The striking pattern brings a vibrant touch, making it perfect for those who embrace uniqueness in their attire. Whether you\'re at a picnic, attending a summer party, or just enjoying a laid-back weekend, this polo shirt fits seamlessly into any relaxed yet trendy ensemble. Perfect for fashion-forwar...',    priceCents: 7247,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68ce17f56d18a047f206316d/112163/106286/stylish-aop-unisex-polo-shirt-vibrant-patterned-shirt-for-casual-outings-summer-vacations-gifts-parties-tropical-vibes.jpg?camera_label=front',    category: "polos",    printifyVariantId: '112163',    sku: '16601521559431485188',    costCents: 4478,  },
  {
    printifyId: '68ce147899d4ee898b0427f9',    name: 'Cream Color Dinger Don',    tagline: 'Cream Color Dinger Don',    description: 'This cream color shirt features Dinger Don, a golfing gopher from Dingersville. Perfect for golf enthusiasts or anyone who loves cute animal characters. Great for casual wear or a day on the golf course. Ideal for gifting on Father\'s Day, birthdays, or golfing events.<br/><br/>Product features<br/>- 100% Polyester fabric for durability and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Extra light fabric for comfort (4.13...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68ce147899d4ee898b0427f9/112163/106286/cream-color-dinger-don.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '24790009021292640543',    costCents: 4478,  },
  {
    printifyId: '68c373b5e14be45566002950',    name: 'Navy Dinger Don',    tagline: 'Navy Dinger Don',    description: 'This Polo Shirt from Dingersville Golf Apparel features our beloved character Dinger Don the Gopher, giving off a fun and sporty vibe. Perfect for golf enthusiasts and those who appreciate quirky designs. Ideal for golf events, casual outings, and everyday wear.<br/><br/>Product features<br/>- 100% Polyester fabric for durability and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choice of white or black thread color<br/>- Lightweight fabric at 4.13 oz/yd² (140g/m²)<br/...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68c373b5e14be45566002950/112163/106286/navy-dinger-don.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '18464535367870694933',    costCents: 4478,  },
  {
    printifyId: '68c3549ce4858a0b710566db',    name: 'Dinger Can Cooler',    tagline: 'Dinger Can Cooler',    description: 'Stay cool and stylish with this fun dingersville can cooler. Perfect for keeping your drinks cold while adding a touch of personality to your gatherings. Ideal for those who enjoy outdoor events, barbecues, parties, and tailgating. Great for summer celebrations, picnics, and sports events.<br/><br/>Product features<br/>- 100% Polyester exterior for durability<br/>- 100% Foam liner interior for stability and grip<br/>- Vibrant colors for a bright and crisp design<br/>- Lightweight and smooth m...',    priceCents: 753,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/68c3549ce4858a0b710566db/78460/38485/dinger-can-cooler.jpg?camera_label=flat-front',    category: "accessories",    printifyVariantId: '78460',    sku: '25642353941259804495',    costCents: 452,  },
  {
    printifyId: '68c34eed303520a4880bddd5',    name: 'Dinger Cooler',    tagline: 'Dinger Cooler',    description: 'Stay cool and stylish on the golf course with this Dingersville Golf cooler bag designed to carry your beers and snacks. Perfect for golf enthusiasts who enjoy a cold drink while playing. Ideal for summer outings, golf tournaments, picnics, and outdoor gatherings.<br/><br/>Product features<br/>- Insulated compartments to hold up to six 12-ounce cans<br/>- Removable, adjustable shoulder strap for easy carrying<br/>- Leak-resistant PEVA lining for added durability<br/>- 2 pockets for extra stor...',    priceCents: 5912,    currency: 'usd',    color: 'Black',    sizes: ['9.75" x 10.5" x 7"'],    image: 'https://images-api.printify.com/mockup/68c34eed303520a4880bddd5/122888/120367/dinger-cooler.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '122887',    sku: '22281184678399858613',    costCents: 3676,  },
  {
    printifyId: '68b8e20091ccadd32e08bfca',    name: 'Fun Golf Vibes Dinger',    tagline: 'Fun Golf Vibes Dinger',    description: 'A vibrant polo shirt featuring the fun vibes of golf, perfect for those who enjoy the sport or want to add a playful touch to their wardrobe. This polo can be worn casually or on the golf course, making it a versatile addition to any golf lover\'s closet. Ideal for golf enthusiasts, Father\'s Day, and casual outings.<br/><br/>Product features<br/>- 100% Polyester fabric for durability and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choice of white or black thread color...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68b8e20091ccadd32e08bfca/112163/106286/fun-golf-vibes-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '33886382232840970994',    costCents: 4478,  },
  {
    printifyId: '68b0ae4f7ce593f16804be9b',    name: 'adidas® Quarter-Zip Pullover (Embroidery)',    tagline: 'adidas® Quarter-Zip Pullover (Embroidery)',    description: '<p>Gear up for performance with the adidas® Quarter-Zip Pullover, a must-have for activewear enthusiasts. Made from 100% recycled polyester, this lightweight, moisture-wicking pullover keeps you cool, dry, and protected from the sun with its UPF 50+ rating.&nbsp;<br><br>Featuring a relaxed fit, self-mock collar, and contrast adidas logo on the left sleeve, it’s both stylish and functional. Ideal for workouts or casual wear, this eco-friendly piece is perfect for custom embroidery, allowing yo...',    priceCents: 10533,    currency: 'usd',    color: 'White',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'],    image: 'https://images-api.printify.com/mockup/68b0ae4f7ce593f16804be9b/118444/109474/adidas-quarter-zip-pullover-embroidery.jpg?camera_label=front',    category: "hoodies",    printifyVariantId: '118444',    sku: '32633084292450909792',    costCents: 6320,  },
  {
    printifyId: '68acb16ceb5eab1df5096758',    name: 'Golfing Animal Dinger',    tagline: 'Golfing Animal Dinger',    description: 'This Polo Shirt features a fun design with lions, tigers, horses, and squids golfing, perfect for those who enjoy a quirky and playful style. It is great for casual outings or sports activities. Ideal for animal lovers and golf enthusiasts. Perfect for birthdays, Father\'s Day, or a unique gift for a golfing buddy.<br/><br/>Product features<br/>- 100% Polyester for durability<br/>- 3 button placket with black or white buttons<br/>- Choice of white or black thread color<br/>- Lightweight fabric...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68acb16ceb5eab1df5096758/112163/106286/golfing-animal-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '12964613204734954717',    costCents: 4478,  },
  {
    printifyId: '68ac919bdf952351270e60af',    name: 'Detroit Style Pizza Dinger',    tagline: 'Detroit Style Pizza Dinger',    description: 'This Polo Shirt features a graphic of a detroit style pizza, perfect for food lovers and casual wear. It gives a fun and relaxed vibe, suitable for everyday wear or pizza-themed events and gatherings. Ideal for both men and women.<br/><br/>Product features<br/>- 100% Polyester fabric for strength and durability<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Extra light fabric for comfort (4.13 oz/yd² (140g/m²))<br/>- Pointed collar fo...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68ac919bdf952351270e60af/112163/106286/detroit-style-pizza-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '21131299028738641437',    costCents: 4478,  },
  {
    printifyId: '68a679eeab64b4f2fe04563f',    name: 'Golf Grief Dinger',    tagline: 'Golf Grief Dinger',    description: 'This Polo Shirt features stages of grief related to golf, perfect for golf enthusiasts looking for a unique and humorous piece to add to their wardrobe. It can be a great conversation starter on the golf course or a fun gift for a golf lover\'s birthday or Father\'s Day.<br/><br/>Product features<br/>- 100% Polyester and extra light fabric for durability and comfort<br/>- 3 button placket with black or white buttons for a customizable look<br/>- Choose between white or black thread color for a ...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a679eeab64b4f2fe04563f/112163/106286/golf-grief-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '74454488184575459609',    costCents: 4478,  },
  {
    printifyId: '68a66c5bfe78bf3d8e06c7df',    name: 'Green and White Mascot Dinger',    tagline: 'Green and White Mascot Dinger',    description: 'This Polo Shirt features our dingersville mascot in a ready-to-fight stance, perfect for golf enthusiasts looking to add a touch of fun to their outfit. The shirt is made of 100% polyester, making it strong, durable, and quick-drying, with a pointed collar and a 3 button placket available in black or white.<br/><br/>Product features<br/>- 100% Polyester fabric for strength and durability<br/>- 3 button placket with black or white buttons<br/>- Choice of white or black thread color<br/>- Light...',    priceCents: 7247,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a66c5bfe78bf3d8e06c7df/112163/106286/green-and-white-mascot-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '16814103502374113787',    costCents: 4478,  },
  {
    printifyId: '68a61128a4bf2d8c400f4376',    name: 'Red Mascot Dinger',    tagline: 'Red Mascot Dinger',    description: 'This Polo Shirt features the dingersville mascot rocking red pants, giving off a fun and quirky vibe. Perfect for casual wear or sporty events, ideal for those who love unique and playful design. Great for gift-giving during birthdays, holidays, or team celebrations.<br/><br/>Product features<br/>- 100% Polyester fabric for strength and durability<br/>- 3 button placket with black or white buttons<br/>- Choice of white or black thread color<br/>- Extra light fabric for comfort (4.13 oz/yd² (1...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a61128a4bf2d8c400f4376/112163/106286/red-mascot-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '11409081806100880657',    costCents: 4478,  },
  {
    printifyId: '68a60d0851a3573a7406aa46',    name: 'Blue and Yellow Mascot Dinger',    tagline: 'Blue and Yellow Mascot Dinger',    description: 'A unisex polo shirt featuring the dingersville mascot golfing in blue and yellow attire. Perfect for golf enthusiasts or sports lovers, this shirt brings a fun and casual vibe. Ideal for casual wear or a day out at the golf course.<br/><br/>Product features<br/>- 100% Polyester fabric for durability and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Lightweight fabric for comfort (4.13 oz/yd²)<br/>- Pointed collar for a p...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a60d0851a3573a7406aa46/112163/106286/blue-and-yellow-mascot-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '24579782374744447273',    costCents: 4478,  },
  {
    printifyId: '68a5f9335fa46329be019778',    name: 'Champagne Golf Bike Shorts',    tagline: 'Champagne Golf Bike Shorts',    description: 'These are women\'s bike shorts designed for golfing, featuring a champagne and elegant print to match a bra top. Perfect for active women looking for stylish and comfortable workout wear. Ideal for golfing and other outdoor activities.<br/><br/>Product features<br/>- 88% polyester, 12% elastane for strength, stretch, and softness<br/>- Without side seams for a smooth, form-fitting look<br/>- All over print for a stylish design<br/>- Thin elastic waistband for a casual look<br/>- Above knee-len...',    priceCents: 3757,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/68a5f9335fa46329be019778/73152/22558/champagne-golf-bike-shorts.jpg?camera_label=front',    category: "shorts",    printifyVariantId: '73152',    sku: '32796172035097309188',    costCents: 2254,  },
  {
    printifyId: '68a528ec763c24fc850e9c0d',    name: 'Champaign Dinger Bra',    tagline: 'Champaign Dinger Bra',    description: 'This sports bra is perfect for active individuals looking for a comfortable and supportive fit. The moisture-wicking material keeps you cool and dry during any physical activity. The dingersville design adds a fun and playful vibe to your workout wardrobe. Ideal for fitness enthusiasts and sports lovers. Great for gym sessions, yoga classes, and jogging in the park.<br/><br/>Product features<br/>- Moisture-wicking material keeps you cool and dry<br/>- Double-layer front and wide elastic band ...',    priceCents: 3499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL'],    image: 'https://images-api.printify.com/mockup/68a528ec763c24fc850e9c0d/73138/18078/champaign-dinger-bra.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '73138',    sku: '16163271156156636233',    costCents: 2536,  },
  {
    printifyId: '68a524fa30c9c878560b6d19',    name: 'Golfing Wolverines Dinger',    tagline: 'Golfing Wolverines Dinger',    description: 'This Polo Shirt features a unique design inspired by the Wolverines golfing, giving off a sporty and casual vibe. It is perfect for casual outings, golf enthusiasts, and sports lovers. Great for Father\'s Day, birthdays, or just to treat yourself.<br/><br/>Product features<br/>- 100% Polyester for durability<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Extra light fabric for comfort<br/>- Pointed collar for a classic look<br/><br/>Ca...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a524fa30c9c878560b6d19/112163/106286/golfing-wolverines-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '13503128600180998119',    costCents: 4478,  },
  {
    printifyId: '68a4da7fd8c4d1e37407c866',    name: 'Good Vibes Dinger',    tagline: 'Good Vibes Dinger',    description: 'A vibrant, all-over print polo shirt featuring a cheerful Dingersville golf theme, including the mascot swinging a club, golf carts, flags, balls, and tropical foliage. Perfect for golf enthusiasts looking to add a pop of color and energy to their wardrobe. Ideal for golf tournaments, Father\'s Day gifts, and summer occasions.<br/><br/>Product features<br/>- 100% Polyester fabric for durability and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choose between white or bl...',    priceCents: 7247,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a4da7fd8c4d1e37407c866/112163/106286/good-vibes-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '74931803055380268154',    costCents: 4478,  },
  {
    printifyId: '68a3f28efa216056080bcd7a',    name: 'Red Coney Dinger',    tagline: 'Red Coney Dinger',    description: 'This funny coney dog inspired polo shirt from the golf brand Dingersville is perfect for those looking to add some humor to their golf attire. The unisex design is relevant for golf lovers and anyone who appreciates a good laugh. Ideal for casual wear on the golf course or for a fun day out with friends. Perfect for Father\'s Day, birthdays, or any golf-related celebrations.<br/><br/>Product features<br/>- 100% Polyester fabric for durability and quick drying<br/>- 3 button placket with black ...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a3f28efa216056080bcd7a/112163/106286/red-coney-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '12896678969807390568',    costCents: 4478,  },
  {
    printifyId: '68a3f04c865f34cdd60984dc',    name: 'White Coney Dinger',    tagline: 'White Coney Dinger',    description: 'This Polo Shirt features a fun coney dog design, perfect for dog lovers who enjoy a playful and unique style. It can be worn casually or dressed up for a fun outing. Ideal for dog owners, animal lovers, and those who appreciate quirky fashion. Relevant for casual wear, dog-themed events, and everyday outings.<br/><br/>Product features<br/>- 100% Polyester for strength and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Ult...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a3f04c865f34cdd60984dc/112163/106286/white-coney-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '23101486354205518151',    costCents: 4478,  },
  {
    printifyId: '68a3ea0a58993f6b4a0539b7',    name: 'Hotdog Dinger',    tagline: 'Hotdog Dinger',    description: 'A hot dog inspired polo shirt designed for golf enthusiasts from the company Dingersville. This shirt exudes a fun and casual vibe, perfect for a day out on the golf course. Ideal for those who appreciate quirky and unique designs. Perfect for golf tournaments, casual Fridays, BBQs, and summer outings.<br/><br/>Product features<br/>- 100% Polyester fabric for strength and quick drying<br/>- 3 button placket with black or white buttons<br/>- Choose between white or black thread color<br/>- Lig...',    priceCents: 5499,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a3ea0a58993f6b4a0539b7/112163/106286/hotdog-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112163',    sku: '17583052203475864024',    costCents: 4478,  },
  {
    printifyId: '68a3e324865f34cdd60981d4',    name: 'Aloha Dinger',    tagline: 'Aloha Dinger',    description: 'This Hawaiian Shirt features a fun golf pattern, perfect for the casual yet stylish look. It is ideal for golf enthusiasts or anyone looking for a laid-back and creative outfit. Perfect for summer gatherings, beach parties, golf outings, and vacations.<br/><br/>Product features<br/>- Full-color 360-degree print for unmatched creativity<br/>- Made with breathable material for comfort<br/>- Structured collar and placket for a polished look<br/>- Available in black or white button options<br/>- ...',    priceCents: 5999,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a3e324865f34cdd60981d4/113123/108681/aloha-dinger.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '113123',    sku: '12063371859308704290',    costCents: 3865,  },
  {
    printifyId: '68a39d400c30e46c2309ca55',    name: 'Dinger Course Polo',    tagline: 'Dinger Course Polo',    description: 'Introducing our vibrant Unisex Polo Shirt, perfect for adding a unique flair to your casual wardrobe. This polo brings a cheerful vibe with its playful design, making it an ideal choice for golf outings, casual Fridays, or weekend brunches. Crafted for comfort and style, it effortlessly blends into any setting, whether you\'re on the course or relaxing with friends. Ideal for both men and women, this shirt is a great gift for golf enthusiasts, adventurers, or anyone who loves to stand out. It\'...',    priceCents: 7247,    currency: 'usd',    color: 'Multi',    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],    image: 'https://images-api.printify.com/mockup/68a39d400c30e46c2309ca55/112163/106286/dinger-course-polo.jpg?camera_label=front',    category: "polos",    printifyVariantId: '112163',    sku: '20385777946570306396',    costCents: 4478,  },
  {
    printifyId: '68914adde13a4265840c0b5a',    name: 'Whimsical Beer-Themed Crew Socks for Fun Days, Perfect Gift for Beer Lovers, Cozy Socks, Unique Party Accessory, Fun Holiday Gift',    tagline: 'Whimsical Beer-Themed Crew Socks for Fun Days, Perfect Gift for Beer Lovers, Cozy Socks, Unique Party Accessory, Fun Holiday Gift',    description: 'Step into comfort and style with these unique crew socks. Featuring a playful design that adds a touch of fun to any outfit, these socks are perfect for casual wear or lounging at home. Made with a blend of durable materials, they ensure a snug fit while keeping your feet cozy. Ideal for anyone who enjoys a blend of comfort and personality in their wardrobe, these socks make a great gift for friends and family during holidays like Christmas, birthdays, or any celebration that calls for a touc...',    priceCents: 1368,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/68914adde13a4265840c0b5a/104469/101489/whimsical-beer-themed-crew-socks-for-fun-days-perfect-gift-for-beer-lovers-cozy-socks-unique-party-accessory-fun-holiday-gift.jpg?camera_label=front',    category: "tees",    printifyVariantId: '104469',    sku: '18205903373970955178',    costCents: 733,  },
  {
    printifyId: '68450b52abde4a754e0c6fcb',    name: 'Dingersville Golf Balls - Perfect for Gifts, Golf Lovers, Tournaments, Casual Play, and Holiday Fun!',    tagline: 'Dingersville Golf Balls - Perfect for Gifts, Golf Lovers, Tournaments, Casual Play, and Holiday Fun!',    description: 'Elevate your golfing experience with these top-quality golf balls. Crafted from durable Surlyn material, they promise remarkable performance on the course. Each set of six features a cohesive design, making them perfect for team outings, corporate events, or casual play with friends. Their sleek, professional appearance is sure to impress other golfers and enhance your game. Ideal for golf enthusiasts, these balls are not just sports equipment; they are also a unique gift choice for holidays ...',    priceCents: 2200,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/68450b52abde4a754e0c6fcb/91860/60899/dingersville-golf-balls-perfect-for-gifts-golf-lovers-tournaments-casual-play-and-holiday-fun.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '91860',    sku: '44183017513645333630',    costCents: 2134,  },
  {
    printifyId: '6844ffc442b468025605b7ed',    name: 'Stylish Golf Towels for Enthusiasts, Perfect Gift for Golf Lovers, Personalized Golf Gift, Unique Golf Course Accessories, Sports [...]',    tagline: 'Stylish Golf Towels for Enthusiasts, Perfect Gift for Golf Lovers, Personalized Golf Gift, Unique Golf Course Accessories, Sports [...]',    description: '<p>Elevate your golf game with our stylish Golf Towels, designed for enthusiasts who appreciate both functionality and flair. Made from a high-quality microfiber blend, these towels are not only ultra-soft but also incredibly absorbent, ensuring your hands and equipment stay dry on the course. The striking print on one side adds a touch of personality, making it a fun accessory for players of all ages. Whether you\'re out on the greens or enjoying a day at the beach, this towel seamlessly fits...',    priceCents: 1640,    currency: 'usd',    color: 'Multi',    sizes: [],    image: 'https://images-api.printify.com/mockup/6844ffc442b468025605b7ed/112488/109916/stylish-golf-towels-for-enthusiasts-perfect-gift-for-golf-lovers-personalized-golf-gift-unique-golf-course-accessories-sports.jpg?camera_label=front',    category: "accessories",    printifyVariantId: '112488',    sku: '10486973722694964515',    costCents: 1061,  },
];

export const byPrintifyId = (id: string) => PRINTIFY_PRODUCTS.find(p => p.printifyId === id);

// Synced 33 of 34 Printify products
// Excludes non-golf items: 1 products